[package]
name = "code"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[[bin]]
name = "code"
path = "code.rs"

[profile.release]
lto = true
strip = false
opt-level = 3
panic = "abort"
codegen-units = 1
debug = true
